# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_S
  - override /env: dmc
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 4
  frame_stack: 5
  action_repeat: 2
  max_episode_steps: -1
  wrapper:
    domain_name: pendulum
    task_name: swingup
    from_vectors: True
    from_pixels: False

# Checkpoint
checkpoint:
  every: 1000

# Buffer
buffer:
  size: 500_000
  checkpoint: True
  memmap: True

# Algorithm
algo:
  total_steps: 100000
  per_rank_batch_size: 64
  cnn_keys:
    encoder: []
    decoder: []
  mlp_keys:
    encoder: [state]
    decoder: [state]
  learning_starts: 1000
  replay_ratio: 0.5

# Metric
metric:
  log_every: 100
  

fabric:
  accelerator: cuda
  precision: bf16-mixed
  # precision: None
  # plugins:
  #   - _target_: lightning.fabric.plugins.precision.MixedPrecision
  #     precision: 16-mixed
  #     device: cuda
  #     scaler:
  #       _target_: torch.cuda.amp.GradScaler
  #       init_scale: 1e4
  #       growth_interval: 1000